# Generated by Django 2.1.5 on 2019-03-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id_categoria_plato', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPlatoPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRestaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=100)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_menu', models.TextField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.TextField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=5000)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('hora_fecha_reserva', models.DateTimeField()),
                ('estado_reserva', models.BooleanField()),
                ('cantidad_personas', models.IntegerField()),
                ('motivo_cancelacion', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id_restaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(max_length=1000)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=700)),
                ('telefono', models.CharField(max_length=8)),
                ('hora_inicio', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('capacidad', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=45)),
                ('apellido_persona', models.CharField(max_length=45)),
                ('direccion', models.TextField(max_length=700)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=8)),
                ('estado', models.BooleanField(default=True)),
                ('codigo_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Sucursal'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Sucursal'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Usuario'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Sucursal'),
        ),
    ]
