# Generated by Django 2.1.5 on 2019-04-10 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fures', '0002_auto_20190409_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Menu'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Sucursal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Sucursal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Usuario'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fures.Restaurante'),
        ),
    ]
